# Generated by Django 5.0.4 on 2024-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generalSettingTitle', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(default='Unknown', null=True)),
            ],
        ),
    ]
