# Generated by Django 5.0.4 on 2024-05-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalsettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='generalSettingTitle',
        ),
    ]
