# Generated by Django 5.0.4 on 2024-04-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_alter_experience_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='companyLogo',
            field=models.ImageField(default=None, upload_to='assets/'),
            preserve_default=False,
        ),
    ]
